# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-01 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=60)),
                ('alias', models.CharField(max_length=50)),
                ('foto', models.ImageField(default='pic_person/None/no-img.jpg', upload_to='pic_person/%Y/%m/%d')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
