# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-21 00:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0003_auto_20171020_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='fechaSubida',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 19, 51, 59, 176838)),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='personaUser',
            field=models.CharField(max_length=250),
        ),
    ]
